// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calculator.proto
// Protobuf Java Version: 4.30.2

package agh.distrib.calculator;

public interface CalcResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.CalcResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double value = 1;</code>
   * @return The value.
   */
  double getValue();
}
