// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calculator.proto
// Protobuf Java Version: 4.30.2

package agh.distrib.calculator;

public final class CalcProto {
  private CalcProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      CalcProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculator_SeqArgs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_calculator_SeqArgs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculator_DefaultArgs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_calculator_DefaultArgs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculator_CalcResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_calculator_CalcResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculator_SingleInt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_calculator_SingleInt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020calculator.proto\022\ncalculator\"\027\n\007SeqArg" +
      "s\022\014\n\004args\030\001 \003(\001\")\n\013DefaultArgs\022\014\n\004arg1\030\001" +
      " \001(\001\022\014\n\004arg2\030\002 \001(\001\"\033\n\nCalcResult\022\r\n\005valu" +
      "e\030\001 \001(\001\"\032\n\tSingleInt\022\r\n\005value\030\001 \001(\0032\347\001\n\n" +
      "Calculator\0222\n\003add\022\023.calculator.SeqArgs\032\026" +
      ".calculator.CalcResult\0226\n\003mul\022\027.calculat" +
      "or.DefaultArgs\032\026.calculator.CalcResult\0226" +
      "\n\003pow\022\027.calculator.DefaultArgs\032\026.calcula" +
      "tor.CalcResult\0225\n\003fib\022\025.calculator.Singl" +
      "eInt\032\025.calculator.SingleInt0\001B%\n\026agh.dis" +
      "trib.calculatorB\tCalcProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_calculator_SeqArgs_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_calculator_SeqArgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_calculator_SeqArgs_descriptor,
        new java.lang.String[] { "Args", });
    internal_static_calculator_DefaultArgs_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_calculator_DefaultArgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_calculator_DefaultArgs_descriptor,
        new java.lang.String[] { "Arg1", "Arg2", });
    internal_static_calculator_CalcResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_calculator_CalcResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_calculator_CalcResult_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_calculator_SingleInt_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_calculator_SingleInt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_calculator_SingleInt_descriptor,
        new java.lang.String[] { "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
