// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calculator.proto
// Protobuf Java Version: 4.30.2

package agh.distrib.calculator;

public interface SeqArgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.SeqArgs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated double args = 1;</code>
   * @return A list containing the args.
   */
  java.util.List<java.lang.Double> getArgsList();
  /**
   * <code>repeated double args = 1;</code>
   * @return The count of args.
   */
  int getArgsCount();
  /**
   * <code>repeated double args = 1;</code>
   * @param index The index of the element to return.
   * @return The args at the given index.
   */
  double getArgs(int index);
}
