// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calculator.proto
// Protobuf Java Version: 4.30.2

package agh.distrib.calculator;

public interface SingleIntOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.SingleInt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 value = 1;</code>
   * @return The value.
   */
  long getValue();
}
