// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calculator.proto
// Protobuf Java Version: 4.30.2

package agh.distrib.calculator;

public interface DefaultArgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.DefaultArgs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double arg1 = 1;</code>
   * @return The arg1.
   */
  double getArg1();

  /**
   * <code>double arg2 = 2;</code>
   * @return The arg2.
   */
  double getArg2();
}
