//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package agh.distrib.SmartHome;

public class DoorsMoving extends com.zeroc.Ice.UserException
{
    public DoorsMoving()
    {
    }

    public DoorsMoving(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::SmartHome::DoorsMoving";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::SmartHome::DoorsMoving", -1, true);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -609568864L;
}
