//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package agh.distrib.SmartHome;

public class DoorsLocked extends com.zeroc.Ice.UserException
{
    public DoorsLocked()
    {
    }

    public DoorsLocked(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::SmartHome::DoorsLocked";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::SmartHome::DoorsLocked", -1, true);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 688386782L;
}
